import { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Link, useRouter } from 'expo-router';
import { colors, radius, shadow, spacing, type } from '@/theme';
import { Alarm, loadAlarms, saveAlarms } from '@/services/storage';

export default function AlarmsScreen() {
  const [alarms, setAlarms] = useState<Alarm[]>([]); const router = useRouter();
  useEffect(() => { loadAlarms().then(setAlarms); }, []);
  const toggle = (id: string, enabled: boolean) => { const next = alarms.map((alarm) => alarm.id === id ? { ...alarm, enabled } : alarm); setAlarms(next); saveAlarms(next); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={type.largeTitle}>Alarms</Text><Text style={styles.subtitle}>Build a morning you can&apos;t snooze.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Add alarm" style={styles.add} onPress={() => Alert.alert('Add alarm', 'Alarm editor is next in the native migration.') }><Ionicons name="add" size={25} color={colors.paper} /></Pressable></View>
    <View style={styles.sectionHeader}><Text style={type.caption}>ACTIVE</Text><Text style={type.caption}>Offline & private</Text></View>
    {alarms.map((alarm) => <Pressable key={alarm.id} onPress={() => router.push({ pathname: '/active-alarm', params: { alarmId: alarm.id } })} style={({ pressed }) => [styles.card, { opacity: pressed ? 0.82 : alarm.enabled ? 1 : 0.58 }]}>
      <View style={styles.row}><View style={{ flex: 1 }}><View style={styles.timeRow}><Text style={styles.time}>{alarm.time}</Text><Text style={styles.period}>AM</Text></View><Text style={styles.label}>{alarm.label} · {alarm.challengeType === 'math' ? `Math (${alarm.mathDifficulty})` : `Shake (${alarm.shakeCountTarget}x)`}</Text></View><Switch value={alarm.enabled} onValueChange={(value) => toggle(alarm.id, value)} trackColor={{ false: '#D8D8D8', true: colors.ink }} thumbColor={colors.paper} /></View>
      <View style={styles.divider} /><View style={styles.bottom}><View style={styles.days}>{alarm.days.map((day, index) => <View key={`${day}-${index}`} style={[styles.day, alarm.enabled && styles.dayActive]}><Text style={[styles.dayText, alarm.enabled && styles.dayTextActive]}>{day}</Text></View>)}</View><Text style={styles.test}>TEST <Ionicons name="play" size={10} color={colors.muted} /></Text></View>
    </Pressable>)}
    <View style={styles.privacy}><Ionicons name="shield-checkmark-outline" size={18} color={colors.ink} /><Text style={styles.privacyText}>No cloud. No tracking. Your alarms stay on this device.</Text></View>
    <Link href="/active-alarm" asChild><Pressable style={styles.debug}><Text style={styles.debugText}>Preview active alarm</Text><Ionicons name="arrow-forward" size={16} color={colors.paper} /></Pressable></Link>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, content: { padding: spacing.lg, gap: spacing.md }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: spacing.sm }, subtitle: { ...type.subhead, marginTop: spacing.xs }, add: { width: 46, height: 46, borderRadius: radius.full, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg }, card: { backgroundColor: colors.paper, borderRadius: radius.lg, padding: spacing.md, borderWidth: 1, borderColor: colors.line, ...shadow.card }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, timeRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6 }, time: { fontSize: 42, fontWeight: '800', color: colors.ink, letterSpacing: -2 }, period: { ...type.caption, color: colors.muted }, label: { ...type.subhead, marginTop: 2 }, divider: { height: 1, backgroundColor: colors.line, marginVertical: spacing.md }, bottom: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, days: { flexDirection: 'row', gap: 5 }, day: { width: 25, height: 25, borderRadius: 13, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' }, dayActive: { backgroundColor: colors.ink }, dayText: { fontSize: 10, fontWeight: '800', color: colors.muted }, dayTextActive: { color: colors.paper }, test: { ...type.caption }, privacy: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center', backgroundColor: colors.soft, padding: spacing.md, borderRadius: radius.md, marginTop: spacing.sm }, privacyText: { ...type.caption, flex: 1 }, debug: { backgroundColor: colors.ink, borderRadius: radius.md, padding: spacing.md, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: spacing.sm, marginTop: spacing.sm }, debugText: { color: colors.paper, fontWeight: '800' } });
