apply plugin: 'com.android.library'

group = 'expo.modules.alarmnative'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyNativeModulesSettingsGradle(project)

android {
  namespace "expo.modules.alarmnative"
  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 24)
    targetSdkVersion safeExtGet('targetSdkVersion', 34)
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'androidx.core:core-ktx:1.13.1'
}
