import { useEffect, useMemo, useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Accelerometer } from 'expo-sensors';
import { colors, radius, spacing, type } from '@/theme';
import { createMathProblem, loadAlarms, Alarm } from '@/services/storage';

export default function Challenge() {
  const router = useRouter(); const { alarmId } = useLocalSearchParams<{ alarmId?: string }>(); const [alarm, setAlarm] = useState<Alarm>(); const [answer, setAnswer] = useState(''); const [problemIndex, setProblemIndex] = useState(0); const [shakeCount, setShakeCount] = useState(0); const [error, setError] = useState(false); const problem = useMemo(() => createMathProblem(alarm?.mathDifficulty ?? 'easy'), [alarm?.mathDifficulty, problemIndex]);
  useEffect(() => { loadAlarms().then((items) => setAlarm(items.find((item) => item.id === alarmId) ?? items[0])); }, [alarmId]);
  useEffect(() => { if (alarm?.challengeType !== 'shake') return; Accelerometer.setUpdateInterval(100); let last = 0; const sub = Accelerometer.addListener(({ x, y, z }) => { const magnitude = Math.sqrt(x*x+y*y+z*z); const now = Date.now(); if (magnitude > 1.8 && now - last > 200) { last = now; setShakeCount((count) => { const next = Math.min(alarm.shakeCountTarget, count + 1); if (next >= alarm.shakeCountTarget) router.replace('/success'); return next; }); } }); return () => sub.remove(); }, [alarm?.challengeType, alarm?.shakeCountTarget, router]);
  const submit = () => { if (Number(answer) === problem.answer) { if (problemIndex + 1 >= (alarm?.mathProblemCount ?? 2)) router.replace('/success'); else { setProblemIndex((value) => value + 1); setAnswer(''); } } else { setError(true); setAnswer(''); } };
  const digit = (value: string) => { setError(false); if (answer.length < 5) setAnswer((current) => current + value); };
  const isMath = alarm?.challengeType !== 'shake'; const target = alarm?.shakeCountTarget ?? 30;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={type.headline}>{isMath ? 'Math puzzle' : 'Shake challenge'}</Text><Text style={type.caption}>{isMath ? `${problemIndex+1} / ${alarm?.mathProblemCount ?? 2}` : `${shakeCount} / ${target}`}</Text></View>{isMath ? <View style={styles.body}><Text style={styles.eyebrow}>SOLVE TO DISMISS</Text><Text style={styles.question}>{problem.question}</Text><View style={[styles.answer, error && styles.answerError]}><Text style={styles.answerText}>{answer || (error ? 'Try again' : '...')}</Text></View><View style={styles.grid}>{['1','2','3','4','5','6','7','8','9','C','0','⌫'].map((value) => <Pressable key={value} style={({ pressed }) => [styles.key, pressed && styles.keyPressed]} onPress={() => value === 'C' ? setAnswer('') : value === '⌫' ? setAnswer((current) => current.slice(0,-1)) : digit(value)}><Text style={styles.keyText}>{value}</Text></Pressable>)}</View><Pressable disabled={!answer} style={[styles.submit, !answer && styles.disabled]} onPress={submit}><Text style={styles.submitText}>Submit answer</Text></Pressable></View> : <View style={styles.body}><View style={styles.shakeCircle}><Text style={styles.percent}>{Math.round(shakeCount / target * 100)}%</Text><Text style={styles.shakeLabel}>{shakeCount} / {target}</Text></View><Text style={styles.shakeTitle}>Shake to unlock</Text><Text style={styles.copy}>Move your phone with full, deliberate shakes. One impulse counts every 200ms.</Text></View>}</SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper,padding:spacing.lg},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingTop:spacing.sm,borderBottomWidth:1,borderBottomColor:colors.line,paddingBottom:spacing.md},body:{flex:1,alignItems:'center',justifyContent:'center'},eyebrow:{...type.caption,letterSpacing:1.4,marginBottom:spacing.sm},question:{fontSize:46,fontWeight:'800',color:colors.ink,marginBottom:spacing.lg},answer:{width:'100%',height:58,borderWidth:2,borderColor:colors.line,borderRadius:radius.sm,alignItems:'center',justifyContent:'center',backgroundColor:colors.soft},answerError:{borderColor:colors.danger},answerText:{fontSize:27,fontWeight:'800',color:colors.ink},grid:{width:'100%',flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginTop:spacing.lg},key:{width:'31%',height:56,borderRadius:radius.sm,borderWidth:1,borderColor:colors.line,backgroundColor:colors.soft,alignItems:'center',justifyContent:'center'},keyPressed:{backgroundColor:colors.ink},keyText:{fontSize:20,fontWeight:'800',color:colors.ink},submit:{width:'100%',height:56,borderRadius:radius.sm,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center',marginTop:spacing.md},disabled:{backgroundColor:'#E3E3E3'},submitText:{color:colors.paper,fontWeight:'800'},shakeCircle:{width:230,height:230,borderRadius:115,borderWidth:14,borderColor:colors.ink,alignItems:'center',justifyContent:'center'},percent:{fontSize:42,fontWeight:'800',color:colors.ink},shakeLabel:{...type.subhead},shakeTitle:{...type.title,marginTop:spacing.xl},copy:{...type.body,color:colors.muted,textAlign:'center',maxWidth:300,lineHeight:24,marginTop:spacing.sm}});
